### ISSUE TITLE
Participant/DX: 91 participants missing diagnosis

### ISSUE THREAD

**Issue by baileyckelly** [d3b-center/d3b-cds-manifest-prep#32]
V0.50
There are 91 subjects in participant but not in diagnosis

**Comment by chris-s-friedman** [comment]
With [release 0.5.3](https://github.com/d3b-center/d3b-cds-manifest-prep/pull/55), all but one participant should now have a diagnosis. `PT_95S99RWE` does not have a diagnosis. doing more investigating on this participant now.

**Comment by chris-s-friedman** [comment]
This participant, `PT_95S99RWE`, has two samples in the [file-sample-participant map file](https://github.com/d3b-center/d3b-cds-manifest-prep/blob/main/cds/data/file_sample_participant_map.csv): 

- `BS_KSFM87N1`
- `BS_YR7Q70YP`

Both of these samples are `Normal` tissue samples. 

Neither of these samples are mapped to a diagnosis in the biospecimen_diagnosis mapping table in the dataservice. 

In the [hostologies file](https://github.com/d3b-center/d3b-cds-manifest-prep/blob/main/cds/data/pbta-histologies.tsv), this participant shows up with two rows: one for a tumor sample not a part of the cds release and a normal sample that _is in the file-sample-participant map_.

I think this _should_ be solved by looking in the histologies file and using the appropriate diagnosis from there. I think the approach used in #54 to solve the issue of what to do when a participant doesn't have a tumor sample in the pbta histologies file needs to be fine tuned. For an extended discussion of the problem with that approach, see [here](https://github.com/d3b-center/d3b-cds-manifest-prep/pull/54#issuecomment-1346690438).

**Comment by chris-s-friedman** [comment]
@baileyckelly with [release 0.6.0](https://github.com/d3b-center/d3b-cds-manifest-prep/releases/tag/0.6.0), this issue should be fixed.
