### ISSUE TITLE
Genomic Info: 1064 non unique library ids in genomic info

### ISSUE THREAD

**Issue by baileyckelly** [d3b-center/d3b-cds-manifest-prep#33]
v0.50 ... File attached

	select count(*) 
	from (select library_id, count(*) 
		  from genomic_info 
		  group by library_id 
		  having count(*) > 1)as_

**Comment by chris-s-friedman** [comment]
This is because some file-sample combinations have multiple sequencing experiments. we handled this last before by having sequencing experiment as part of the ID here. 

I'm working on adding sequencing experiment id back in to the library ID
