### ISSUE TITLE
Genomic Info: 7301 files with an instrument model not in the enum list

### ISSUE THREAD

**Issue by baileyckelly** [d3b-center/d3b-cds-manifest-prep#35]
These values are not in the approved enum list. This test previously passed.

platform | count
"hiseq"	98
"dnbseq"	42
"not reported"	6860
"hiseq x"	301

**Comment by chris-s-friedman** [comment]
May need to go back to bix with a data ask for these files. [here](https://github.com/d3b-center/d3b-cds-manifest-prep/blob/main/cds/data/BS_SeqCenter_Platform_Model.xlsx), bix mapped specimens to sequencing center, platform, and instrument model. For consistency maybe we want to have this mapping from bix for all samples?
